/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module FresnelApp {
    /** Generated from Envivo.Fresnel.UiCore.Commands.BaseCommandResponse **/
    export interface BaseCommandResponse {
        Passed: boolean;
        Failed: boolean;
        Messages: FresnelApp.MessageVM[];
        Modifications: FresnelApp.ModificationsVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.CollectionAddNewRequest **/
    export interface CollectionAddNewRequest {
        ParentObjectID: any;
        CollectionPropertyName: string;
        ElementTypeName: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.CollectionAddRequest **/
    export interface CollectionAddRequest {
        ParentObjectID: any;
        CollectionPropertyName: string;
        ElementIDs: any[];
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.CollectionAddResponse **/
    export interface CollectionAddResponse extends FresnelApp.BaseCommandResponse {
        AddedItem: FresnelApp.ObjectVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.CollectionRemoveRequest **/
    export interface CollectionRemoveRequest {
        ParentObjectID: any;
        CollectionPropertyName: string;
        ElementID: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.CreateAndSetPropertyRequest **/
    export interface CreateAndSetPropertyRequest {
        ObjectID: any;
        PropertyName: string;
        ClassTypeName: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.CreateAndSetPropertyResponse **/
    export interface CreateAndSetPropertyResponse extends FresnelApp.BaseCommandResponse {
        NewObject: FresnelApp.ObjectVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.CreateCommandResponse **/
    export interface CreateCommandResponse extends FresnelApp.BaseCommandResponse {
        NewObject: FresnelApp.ObjectVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.CreateRequest **/
    export interface CreateRequest {
        ParentObjectID: any;
        ClassTypeName: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.GenericResponse **/
    export interface GenericResponse extends FresnelApp.BaseCommandResponse {
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.GetObjectRequest **/
    export interface GetObjectRequest {
        ObjectID: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.GetPropertyRequest **/
    export interface GetPropertyRequest {
        ObjectID: any;
        PropertyName: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.GetPropertyResponse **/
    export interface GetPropertyResponse extends FresnelApp.BaseCommandResponse {
        ReturnValue: FresnelApp.ObjectVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.InvokeMethodRequest **/
    export interface InvokeMethodRequest {
        ObjectID: any;
        MethodName: string;
        Parameters: FresnelApp.ParameterVM[];
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.InvokeMethodResponse **/
    export interface InvokeMethodResponse extends FresnelApp.BaseCommandResponse {
        ResultObject: FresnelApp.ObjectVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SaveChangesRequest **/
    export interface SaveChangesRequest {
        ObjectID: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SaveChangesResponse **/
    export interface SaveChangesResponse extends FresnelApp.BaseCommandResponse {
        SavedObjects: FresnelApp.ObjectVM[];
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SearchObjectsRequest **/
    export interface SearchObjectsRequest extends FresnelApp.SearchRequest {
        SearchType: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SearchParameterRequest **/
    export interface SearchParameterRequest extends FresnelApp.SearchRequest {
        ObjectID: any;
        MethodName: string;
        ParameterName: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SearchPropertyRequest **/
    export interface SearchPropertyRequest extends FresnelApp.SearchRequest {
        ObjectID: any;
        PropertyName: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SearchRequest **/
    export interface SearchRequest {
        SearchFilters: FresnelApp.SearchFilter[];
        OrderBy: string;
        IsDescendingOrder: boolean;
        PageSize: number;
        PageNumber: number;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SearchFilter **/
    export interface SearchFilter {
        PropertyName: string;
        FilterValue: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SearchResponse **/
    export interface SearchResponse extends FresnelApp.BaseCommandResponse {
        Result: FresnelApp.SearchResultsVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SetParameterRequest **/
    export interface SetParameterRequest {
        ObjectID: any;
        MethodName: string;
        ParameterName: string;
        NonReferenceValue: any;
        ReferenceValueId: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Commands.SetPropertyRequest **/
    export interface SetPropertyRequest {
        ObjectID: any;
        PropertyName: string;
        NonReferenceValue: any;
        ReferenceValueId: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.BaseViewModel **/
    export interface BaseViewModel {
        IsVisible: boolean;
        IsEnabled: boolean;
        Name: string;
        Description: string;
        Error: string;
        Tooltip: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.Changes.CollectionElementVM **/
    export interface CollectionElementVM {
        CollectionId: any;
        ElementId: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.Changes.ModificationsVM **/
    export interface ModificationsVM {
        NewObjects: FresnelApp.ObjectVM[];
        PropertyChanges: FresnelApp.PropertyChangeVM[];
        ObjectTitleChanges: FresnelApp.ObjectTitleChangeVM[];
        CollectionAdditions: FresnelApp.CollectionElementVM[];
        CollectionRemovals: FresnelApp.CollectionElementVM[];
        MethodParameterChanges: FresnelApp.ParameterChangeVM[];
        SavedObjects: FresnelApp.ObjectVM[];
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.Changes.ObjectTitleChangeVM **/
    export interface ObjectTitleChangeVM {
        ObjectId: any;
        Title: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.Changes.ParameterChangeVM **/
    export interface ParameterChangeVM {
        ObjectId: any;
        MethodName: string;
        ParameterName: string;
        State: FresnelApp.ValueStateVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.Changes.PropertyChangeVM **/
    export interface PropertyChangeVM {
        ObjectId: any;
        PropertyName: string;
        State: FresnelApp.ValueStateVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.Classes.ClassItem **/
    export interface ClassItem extends FresnelApp.BaseViewModel {
        Type: string;
        FullTypeName: string;
        Create: FresnelApp.InteractionPoint;
        Search: FresnelApp.InteractionPoint;
        RepositoryCommands: FresnelApp.InteractionPoint[];
        StaticMethodCommands: FresnelApp.InteractionPoint[];
        FactoryCommands: FresnelApp.InteractionPoint[];
        ServiceCommands: FresnelApp.InteractionPoint[];
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.Classes.Namespace **/
    export interface Namespace extends FresnelApp.BaseViewModel {
        FullName: string;
        Classes: FresnelApp.ClassItem[];
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.CollectionVM **/
    export interface CollectionVM extends FresnelApp.ObjectVM {
        IsCollection: boolean;
        ElementType: string;
        ElementProperties: FresnelApp.PropertyVM[];
        Items: FresnelApp.ObjectVM[];
        DisplayItems: FresnelApp.ObjectVM[];
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.DirtyStateVM **/
    export interface DirtyStateVM {
        IsTransient: boolean;
        IsPersistent: boolean;
        IsDirty: boolean;
        HasDirtyChildren: boolean;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.InteractionPoint **/
    export interface InteractionPoint extends FresnelApp.BaseViewModel {
        CommandUri: string;
        CommandArg: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.MessageVM **/
    export interface MessageVM {
        OccurredAt: string;
        Text: string;
        Detail: string;
        RequiresAcknowledgement: boolean;
        IsSuccess: boolean;
        IsInfo: boolean;
        IsWarning: boolean;
        IsError: boolean;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.MethodVM **/
    export interface MethodVM extends FresnelApp.BaseViewModel {
        ObjectID?: any;
        Index: number;
        InternalName: string;
        Parameters: FresnelApp.ParameterVM[];
        ParametersSetByUser: FresnelApp.ParameterVM[];
        IsAsync: boolean;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.ObjectVM **/
    export interface ObjectVM extends FresnelApp.BaseViewModel {
        ID: any;
        Type: string;
        Properties: FresnelApp.PropertyVM[];
        Methods: FresnelApp.MethodVM[];
        IsPersistable: boolean;
        DirtyState: FresnelApp.DirtyStateVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.ParameterVM **/
    export interface ParameterVM extends FresnelApp.SettableMemberVM {
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.PropertyVM **/
    export interface PropertyVM extends FresnelApp.SettableMemberVM {
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.SearchResultItemVM **/
    export interface SearchResultItemVM extends FresnelApp.ObjectVM {
        IsSelected: boolean;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.SearchResultsVM **/
    export interface SearchResultsVM extends FresnelApp.CollectionVM {
        IsSearchResults: boolean;
        OriginalRequest: FresnelApp.SearchRequest;
        AreMoreAvailable: boolean;
        AllowSelection: boolean;
        AllowMultiSelect: boolean;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.SessionVM **/
    export interface SessionVM {
        UserName: string;
        LogonTime: string;
        Messages: FresnelApp.MessageVM[];
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.SettableMemberVM **/
    export interface SettableMemberVM extends FresnelApp.BaseViewModel {
        ObjectID?: any;
        Index: number;
        InternalName: string;
        AllowedClassTypes: string[];
        IsRequired: boolean;
        IsLoaded: boolean;
        IsObject: boolean;
        IsCollection: boolean;
        IsNonReference: boolean;
        Info: any;
        State: FresnelApp.ValueStateVM;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.TypeInfo.BooleanVM **/
    export interface BooleanVM {
        Name: string;
        PreferredControl: any;
        IsNullable: boolean;
        TrueValue: string;
        FalseValue: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.TypeInfo.DateTimeVM **/
    export interface DateTimeVM {
        Name: string;
        PreferredControl: any;
        CustomFormat: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.TypeInfo.EnumItemVM **/
    export interface EnumItemVM extends FresnelApp.BaseViewModel {
        EnumName: string;
        Value: number;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.TypeInfo.EnumVM **/
    export interface EnumVM {
        Name: string;
        IsBitwiseEnum: boolean;
        Items: FresnelApp.EnumItemVM[];
        PreferredControl: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.TypeInfo.NullVM **/
    export interface NullVM {
        Name: string;
        PreferredControl: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.TypeInfo.NumberVM **/
    export interface NumberVM {
        Name: string;
        PreferredControl: any;
        MinValue: number;
        MaxValue: number;
        DecimalPlaces: number;
        CurrencySymbol: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.TypeInfo.ReferenceTypeVM **/
    export interface ReferenceTypeVM {
        FullTypeName: string;
        PreferredControl: any;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.TypeInfo.StringVM **/
    export interface StringVM {
        Name: string;
        PreferredControl: any;
        MinLength: number;
        MaxLength: number;
        EditMask: string;
    }
    /** Generated from Envivo.Fresnel.UiCore.Model.ValueStateVM **/
    export interface ValueStateVM {
        Value: any;
        ReferenceValueID?: any;
        FriendlyValue: string;
        ValueType: string;
        Get: FresnelApp.InteractionPoint;
        Set: FresnelApp.InteractionPoint;
        Create: FresnelApp.InteractionPoint;
        Clear: FresnelApp.InteractionPoint;
        Add: FresnelApp.InteractionPoint;
    }
}
